<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$OrderColors = \Magento\Framework\App\ObjectManager::getInstance()
    ->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
    ->getValue(
        'orderstatusmanagement/color/fields',
        \Magento\Store\Model\ScopeInterface::SCOPE_STORE,
    );
	//echo "<pre>";
	$OrderColors= json_decode($OrderColors);

?>
<style>
.data-grid td
{
border-width: 0 1px 1px 0;
border-color: #dadfe0;
border-style: solid;
padding: 2px 4px 2px 4px; 
}
<?php
 foreach ($OrderColors as $key => $object) {
    //echo $object->background_color;
	echo 'td.'.strtolower($object->order_status) .'{'.'background-color:'.$object->background_color.';color:'.$object->text_color.';}';
	echo '.data-grid tr:hover td.'.strtolower($object->order_status).' {background-color: '.$object->background_color_hover.';color:'.$object->text_color_hover.'; opacity: .9}';
	echo 'td.'.strtolower($object->order_status).' a{color: #003aff;}';
}

?>
td.on-mouse {opacity: .9}
.data-grid tr:hover td.on-mouse {opacity: .9}
.sales-order-index .pointer
{
cursor: pointer;
}
</style>